spring:
  application: pruebagmr

server:
  port: 8081

logging:
  level:
    root: INFO
    org.gmr.app.oraclemoonapp: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"